export interface DcfNode {
  id: string
  label: string
  shortLabel?: string
  formula?: string
  operator?: '+' | '−' | '×'
  definition: string
  children?: string[]
  kbAreaIds?: string[]
  kbCategory?: string
  defaultValue?: number
  unit?: string
}

export const DCF_NODES: Record<string, DcfNode> = {
  fcf: {
    id: 'fcf',
    label: 'Free Cash Flow',
    shortLabel: 'FCF',
    formula: 'OCF − CapEx',
    definition: 'Cash available to equity holders after all operating expenses and capital investments. This is the value that gets discounted back to present in a DCF model.',
    children: ['ocf', 'capex'],
  },
  ocf: {
    id: 'ocf',
    label: 'Operating Cash Flow',
    shortLabel: 'OCF',
    formula: 'Fleet Size × Unit Economics',
    definition: 'Cash generated from core robotaxi operations before capital investments. Decomposed into scale (how many vehicles) and unit economics (how much each one nets).',
    children: ['fleet_size', 'unit_economics'],
  },
  fleet_size: {
    id: 'fleet_size',
    label: 'Fleet Size',
    definition: 'Number of active robotaxi vehicles generating revenue. Currently ramping in Austin and Bay Area, with geographic expansion underway.',
    kbAreaIds: ['fleet_deployment'],
    kbCategory: 'Robotaxi',
  },
  unit_economics: {
    id: 'unit_economics',
    label: 'Unit Economics',
    formula: 'Revenue/Vehicle − Cost/Vehicle − Tax/Vehicle',
    definition: 'Net cash generated per vehicle per year after all operating costs and taxes. This is the margin story — how profitable is each robotaxi unit.',
    children: ['rev_per_vehicle', 'cost_per_vehicle', 'tax_per_vehicle'],
  },
  rev_per_vehicle: {
    id: 'rev_per_vehicle',
    label: 'Revenue per Vehicle',
    shortLabel: 'Rev/Vehicle',
    formula: 'Trips/Day × Revenue/Trip × 365',
    definition: 'Annual fare revenue generated by a single robotaxi. Driven by how many trips it completes per day and how much each trip earns.',
    children: ['trips_per_day', 'rev_per_trip'],
    unit: '$/yr',
  },
  trips_per_day: {
    id: 'trips_per_day',
    label: 'Trips per Day',
    formula: 'Active Hours / Time per Trip Cycle',
    definition: 'Number of completed fare trips per vehicle per day. Determined by how many hours the vehicle is in the network and how long each full trip cycle takes (driving + repositioning + loading).',
    children: ['active_hours', 'trip_cycle_time'],
    unit: 'trips',
  },
  active_hours: {
    id: 'active_hours',
    label: 'Active Hours per Day',
    formula: 'Utilization × 24',
    definition: 'Hours per day the vehicle is in the network serving or waiting for rides. At 30% utilization = 7.2 hours/day. Remaining time covers charging, maintenance, and low-demand periods.',
    children: ['utilization'],
    unit: 'hrs',
  },
  utilization: {
    id: 'utilization',
    label: 'Utilization Rate',
    definition: 'Percentage of the day the vehicle is active in the network. Base assumption: 30%. Conservative — leaves ample time for charging and off-peak downtime.',
    kbAreaIds: ['ride_volume'],
    kbCategory: 'Robotaxi',
    defaultValue: 30,
    unit: '%',
  },
  trip_cycle_time: {
    id: 'trip_cycle_time',
    label: 'Trip Cycle Time',
    formula: 'Drive Time + Empty Repositioning + Load/Unload',
    definition: 'Total time from accepting one ride to being ready for the next. Includes the fare-generating drive, deadhead miles to the next pickup, and passenger loading/unloading.',
    children: ['drive_time', 'repositioning_time', 'load_unload_time'],
    unit: 'min',
  },
  drive_time: {
    id: 'drive_time',
    label: 'Drive Time',
    formula: 'Avg Trip Length / Avg Speed',
    definition: 'Time spent driving the passenger. At 5 miles average trip and 25 mph average speed = 12 minutes.',
    children: ['avg_trip_length', 'avg_speed'],
    unit: 'min',
  },
  avg_trip_length: {
    id: 'avg_trip_length',
    label: 'Avg Trip Length',
    definition: 'Average distance per fare trip. Base assumption: 5 miles.',
    defaultValue: 5,
    unit: 'mi',
  },
  avg_speed: {
    id: 'avg_speed',
    label: 'Avg Travel Speed',
    definition: 'Average speed during trips including traffic, stops, and urban driving. Base assumption: 25 mph.',
    defaultValue: 25,
    unit: 'mph',
  },
  repositioning_time: {
    id: 'repositioning_time',
    label: 'Empty Repositioning',
    formula: 'Avg Empty Distance / Avg Speed',
    definition: 'Time spent driving empty to the next pickup. At 2 miles deadhead and 25 mph = 4.8 minutes. This is a function of demand density, not trip length.',
    children: ['avg_empty_distance'],
    unit: 'min',
  },
  avg_empty_distance: {
    id: 'avg_empty_distance',
    label: 'Avg Empty Distance',
    definition: 'Average deadhead miles between dropping off one passenger and picking up the next. Base assumption: 2 miles. Driven by demand density and geographic coverage.',
    defaultValue: 2,
    unit: 'mi',
  },
  load_unload_time: {
    id: 'load_unload_time',
    label: 'Load/Unload Time',
    definition: 'Time for passenger boarding and exiting. Base assumption: 3 minutes per trip cycle.',
    defaultValue: 3,
    unit: 'min',
  },
  rev_per_trip: {
    id: 'rev_per_trip',
    label: 'Revenue per Trip',
    formula: 'Base Fare + (Trip Length × Fare/Mile)',
    definition: 'Fare collected per trip. At $3 base + 5 miles × $1.40/mile = $10.00 per trip. Conservative vs current rideshare rates.',
    children: ['base_fare', 'fare_per_mile'],
    kbAreaIds: ['pricing_revenue'],
    kbCategory: 'Robotaxi',
    unit: '$',
  },
  base_fare: {
    id: 'base_fare',
    label: 'Base Fare',
    definition: 'Fixed starting fare per trip. Base assumption: $3.00.',
    kbAreaIds: ['pricing_revenue'],
    kbCategory: 'Robotaxi',
    defaultValue: 3,
    unit: '$',
  },
  fare_per_mile: {
    id: 'fare_per_mile',
    label: 'Fare per Mile',
    definition: 'Per-mile charge on top of base fare. Base assumption: $1.40/mile.',
    kbAreaIds: ['pricing_revenue'],
    kbCategory: 'Robotaxi',
    defaultValue: 1.4,
    unit: '$/mi',
  },
  cost_per_vehicle: {
    id: 'cost_per_vehicle',
    label: 'Cost per Vehicle',
    shortLabel: 'Cost/Vehicle',
    definition: 'Annual operating cost per vehicle. Includes insurance, maintenance, cleaning, connectivity, remote operations, and electricity. To be detailed.',
    kbAreaIds: ['operating_costs'],
    kbCategory: 'Robotaxi',
  },
  tax_per_vehicle: {
    id: 'tax_per_vehicle',
    label: 'Tax per Vehicle',
    shortLabel: 'Tax/Vehicle',
    definition: 'Per-vehicle share of corporate income tax on operating profit. Applied as effective tax rate on (Revenue − Cost) per vehicle.',
  },
  capex: {
    id: 'capex',
    label: 'Capital Expenditures',
    shortLabel: 'CapEx',
    formula: 'Vehicle Purchases + Infrastructure',
    definition: 'Upfront investment in fleet vehicles and supporting infrastructure. Heavy in early years, decreases as fleet matures.',
    children: ['vehicle_purchases', 'infrastructure'],
  },
  vehicle_purchases: {
    id: 'vehicle_purchases',
    label: 'Vehicle Purchases',
    formula: 'New Units × Cost per Vehicle',
    definition: 'Cost of acquiring new Cybercabs or Model Ys for the fleet. Cybercab target cost ~$30k, significantly below competitors.',
    kbAreaIds: ['vehicle_capex', 'production_manufacturing'],
    kbCategory: 'Robotaxi',
  },
  infrastructure: {
    id: 'infrastructure',
    label: 'Infrastructure',
    definition: 'Charging depots, cleaning facilities, and remote operations centers needed to support the fleet.',
  },
}

export const DCF_ROOT = 'fcf'

// ── Revenue per Vehicle computation ──────────────────────

/** IDs of all leaf inputs in the rev_per_vehicle subtree */
export const REV_INPUT_IDS = [
  'utilization', 'avg_trip_length', 'avg_speed',
  'avg_empty_distance', 'load_unload_time', 'base_fare', 'fare_per_mile',
] as const

export type RevInputId = typeof REV_INPUT_IDS[number]

/** Compute all rev_per_vehicle intermediate + final values from leaf inputs */
export function computeRevPerVehicle(overrides: Partial<Record<RevInputId, number>> = {}): Record<string, number> {
  const v = (id: RevInputId) => overrides[id] ?? DCF_NODES[id].defaultValue!

  const utilization = v('utilization') / 100
  const active_hours = utilization * 24
  const drive_time = (v('avg_trip_length') / v('avg_speed')) * 60
  const repositioning_time = (v('avg_empty_distance') / v('avg_speed')) * 60
  const trip_cycle_time = drive_time + repositioning_time + v('load_unload_time')
  const trips_per_day = (active_hours * 60) / trip_cycle_time
  const rev_per_trip = v('base_fare') + v('avg_trip_length') * v('fare_per_mile')
  const rev_per_vehicle = trips_per_day * rev_per_trip * 365

  return {
    utilization: v('utilization'),
    active_hours,
    avg_trip_length: v('avg_trip_length'),
    avg_speed: v('avg_speed'),
    drive_time,
    avg_empty_distance: v('avg_empty_distance'),
    repositioning_time,
    load_unload_time: v('load_unload_time'),
    trip_cycle_time,
    trips_per_day,
    base_fare: v('base_fare'),
    fare_per_mile: v('fare_per_mile'),
    rev_per_trip,
    rev_per_vehicle,
  }
}

/** Format a computed value with its unit */
export function formatDcfValue(nodeId: string, value: number): string {
  const node = DCF_NODES[nodeId]
  const unit = node?.unit
  if (unit === '$') return `$${value.toFixed(2)}`
  if (unit === '$/yr') return `$${Math.round(value).toLocaleString()}`
  if (unit === '$/mi') return `$${value.toFixed(2)}/mi`
  if (unit === '%') return `${value}%`
  if (unit === 'min') return `${value.toFixed(1)} min`
  if (unit === 'hrs') return `${value.toFixed(1)} hrs`
  if (unit === 'mph') return `${value} mph`
  if (unit === 'mi') return `${value} mi`
  if (unit === 'trips') return `${value.toFixed(1)}`
  return `${value}`
}
