export interface DcfNode {
  id: string
  label: string
  shortLabel?: string
  formula?: string
  operator?: '+' | '−' | '×'
  definition: string
  children?: string[]
  kbAreaIds?: string[]
  kbCategory?: string
  defaultValue?: number
  unit?: string
}

export const DCF_NODES: Record<string, DcfNode> = {
  dcf: {
    id: 'dcf',
    label: 'Discounted Cash Flow',
    shortLabel: 'DCF',
    formula: 'Σ PV(FCF) + PV(Terminal Value)',
    definition: 'Present value of all projected free cash flows over 10 years, plus a terminal value capturing all cash flows beyond Year 10. Each year\'s FCF is discounted back at the WACC to reflect the time value of money and risk.',
    children: ['fcf'],
  },
  fcf: {
    id: 'fcf',
    label: 'Free Cash Flow',
    shortLabel: 'FCF',
    formula: 'OCF − CapEx',
    definition: 'Cash available to equity holders after all operating expenses and capital investments. This is the value that gets discounted back to present in a DCF model.',
    children: ['ocf', 'capex'],
    unit: '$total',
  },
  ocf: {
    id: 'ocf',
    label: 'Operating Cash Flow',
    shortLabel: 'OCF',
    formula: 'Fleet Size × Unit Economics',
    definition: 'Cash generated from core robotaxi operations before capital investments. Decomposed into scale (how many vehicles) and unit economics (how much each one nets).',
    children: ['fleet_size', 'unit_economics'],
    unit: '$total',
  },
  fleet_size: {
    id: 'fleet_size',
    label: 'Fleet Size',
    definition: 'Number of active robotaxi vehicles generating revenue. Currently ramping in Austin and Bay Area, with geographic expansion underway.',
    unit: 'vehicles',
  },
  unit_economics: {
    id: 'unit_economics',
    label: 'Unit Economics',
    formula: 'Revenue/Vehicle − Cost/Vehicle − Tax/Vehicle',
    definition: 'Net cash generated per vehicle per year after all operating costs and taxes. This is the margin story — how profitable is each robotaxi unit.',
    children: ['rev_per_vehicle', 'cost_per_vehicle', 'tax_per_vehicle'],
    unit: '$/yr',
  },
  rev_per_vehicle: {
    id: 'rev_per_vehicle',
    label: 'Revenue per Vehicle',
    shortLabel: 'Rev/Vehicle',
    formula: 'Trips/Day × Revenue/Trip × 365',
    definition: 'Annual fare revenue generated by a single robotaxi. Driven by how many trips it completes per day and how much each trip earns.',
    children: ['trips_per_day', 'rev_per_trip'],
    unit: '$/yr',
  },
  trips_per_day: {
    id: 'trips_per_day',
    label: 'Trips per Day',
    formula: 'Active Hours / Time per Trip Cycle',
    definition: 'Number of completed fare trips per vehicle per day. Determined by how many hours the vehicle is in the network and how long each full trip cycle takes (driving + repositioning + loading).',
    children: ['active_hours', 'trip_cycle_time'],
    unit: 'trips',
  },
  active_hours: {
    id: 'active_hours',
    label: 'Active Hours per Day',
    formula: 'Utilization × 24',
    definition: 'Hours per day the vehicle is in the network serving or waiting for rides. At 30% utilization = 7.2 hours/day. Remaining time covers charging, maintenance, and low-demand periods.',
    children: ['utilization'],
    unit: 'hrs',
  },
  utilization: {
    id: 'utilization',
    label: 'Utilization Rate',
    definition: 'Percentage of the day the vehicle is active in the network. Base assumption: 30%. Conservative — leaves ample time for charging and off-peak downtime.',
    defaultValue: 30,
    unit: '%',
  },
  trip_cycle_time: {
    id: 'trip_cycle_time',
    label: 'Trip Cycle Time',
    formula: 'Drive Time + Empty Repositioning + Load/Unload',
    definition: 'Total time from accepting one ride to being ready for the next. Includes the fare-generating drive, deadhead miles to the next pickup, and passenger loading/unloading.',
    children: ['drive_time', 'repositioning_time', 'load_unload_time'],
    unit: 'min',
  },
  drive_time: {
    id: 'drive_time',
    label: 'Drive Time',
    formula: 'Avg Trip Length / Avg Speed',
    definition: 'Time spent driving the passenger. At 5 miles average trip and 25 mph average speed = 12 minutes.',
    children: ['avg_trip_length', 'avg_speed'],
    unit: 'min',
  },
  avg_trip_length: {
    id: 'avg_trip_length',
    label: 'Avg Trip Length',
    definition: 'Average distance per fare trip. Base assumption: 5 miles.',
    defaultValue: 5,
    unit: 'mi',
  },
  avg_speed: {
    id: 'avg_speed',
    label: 'Avg Travel Speed',
    definition: 'Average speed during trips including traffic, stops, and urban driving. Base assumption: 25 mph.',
    defaultValue: 25,
    unit: 'mph',
  },
  repositioning_time: {
    id: 'repositioning_time',
    label: 'Empty Repositioning',
    formula: 'Avg Empty Distance / Avg Speed',
    definition: 'Time spent driving empty to the next pickup. At 2 miles deadhead and 25 mph = 4.8 minutes. This is a function of demand density, not trip length.',
    children: ['avg_empty_distance'],
    unit: 'min',
  },
  avg_empty_distance: {
    id: 'avg_empty_distance',
    label: 'Avg Empty Distance',
    definition: 'Average deadhead miles between dropping off one passenger and picking up the next. Base assumption: 2 miles. Driven by demand density and geographic coverage.',
    defaultValue: 2,
    unit: 'mi',
  },
  load_unload_time: {
    id: 'load_unload_time',
    label: 'Load/Unload Time',
    definition: 'Time for passenger boarding and exiting. Base assumption: 3 minutes per trip cycle.',
    defaultValue: 3,
    unit: 'min',
  },
  rev_per_trip: {
    id: 'rev_per_trip',
    label: 'Revenue per Trip',
    formula: 'Base Fare + (Trip Length × Fare/Mile)',
    definition: 'Fare collected per trip. At $3 base + 5 miles × $1.40/mile = $10.00 per trip. Conservative vs current rideshare rates.',
    children: ['base_fare', 'fare_per_mile'],
    unit: '$',
  },
  base_fare: {
    id: 'base_fare',
    label: 'Base Fare',
    definition: 'Fixed starting fare per trip. Base assumption: $3.00.',
    defaultValue: 3,
    unit: '$',
  },
  fare_per_mile: {
    id: 'fare_per_mile',
    label: 'Fare per Mile',
    definition: 'Per-mile charge on top of base fare. Base assumption: $1.40/mile.',
    defaultValue: 1.4,
    unit: '$/mi',
  },
  cost_per_vehicle: {
    id: 'cost_per_vehicle',
    label: 'Cost per Vehicle',
    shortLabel: 'Cost/Vehicle',
    formula: 'Charging + Maintenance + Insurance + Remote Ops + Cleaning + Connectivity + Parking + Overhead',
    definition: 'Annual operating cost per vehicle. Includes charging, maintenance, insurance, remote operations, cleaning, connectivity, depot parking, and overhead.',
    children: ['annual_distance', 'charging_cost', 'maintenance_cost', 'insurance_cost', 'remote_ops_cost', 'cleaning_cost', 'connectivity_cost', 'parking_cost', 'overhead_cost'],
    unit: '$/yr',
  },
  annual_distance: {
    id: 'annual_distance',
    label: 'Annual Distance',
    formula: 'Trips/Day × (Trip Length + Empty Distance) × 365',
    definition: 'Total miles driven per vehicle per year, including both fare-generating and deadhead (repositioning) miles. Shared input for charging and maintenance cost calculations.',
    unit: 'mi/yr',
  },
  charging_cost: {
    id: 'charging_cost',
    label: 'Charging Cost',
    formula: 'Annual Distance × kWh/Mile × $/kWh',
    definition: 'Annual electricity cost to charge the vehicle. Driven by total miles driven (fare + deadhead), energy efficiency, and electricity price. Tesla\'s Supercharger network and off-peak charging strategies can significantly reduce this cost.',
    children: ['kwh_per_mile', 'price_per_kwh'],
    unit: '$/yr',
  },
  kwh_per_mile: {
    id: 'kwh_per_mile',
    label: 'Energy Consumption',
    definition: 'Energy used per mile driven. Cybercab is purpose-built for efficiency — smaller, lighter, no steering wheel. Base assumption: 0.25 kWh/mile (~4 mi/kWh).',
    defaultValue: 0.25,
    unit: 'kWh/mi',
  },
  price_per_kwh: {
    id: 'price_per_kwh',
    label: 'Electricity Price',
    definition: 'Cost per kilowatt-hour for fleet charging. Tesla owns the Supercharger network and can charge at cost, but not all charging will be off-peak or at owned depots. Base assumption: $0.12/kWh (blended rate — fleet models cite $0.16–$0.35, but Tesla fleet-owned infrastructure is significantly cheaper).',
    defaultValue: 0.12,
    unit: '$/kWh',
  },
  maintenance_cost: {
    id: 'maintenance_cost',
    label: 'Maintenance Cost',
    formula: 'Tire Cost + General Maintenance',
    definition: 'Annual maintenance cost per vehicle. EVs have significantly lower maintenance than ICE vehicles — no oil changes, minimal brake wear due to regenerative braking. Main items: tires (largest cost), brakes, cabin filter, wipers, 12V battery, coolant, suspension.',
    children: ['tire_cost', 'general_maintenance'],
    unit: '$/yr',
  },
  tire_cost: {
    id: 'tire_cost',
    label: 'Tire Cost',
    formula: 'Annual Distance ÷ Tire Life × Cost per Set',
    definition: 'Annual tire replacement cost. EV tires wear faster than ICE due to vehicle weight and instant torque. Urban robotaxi driving at moderate speeds is gentler than highway, but high annual mileage means frequent replacement.',
    children: ['tire_life', 'tire_set_cost'],
    unit: '$/yr',
  },
  tire_life: {
    id: 'tire_life',
    label: 'Tire Life',
    definition: 'Miles per set of tires before replacement. EV-specific tires typically last 25,000–35,000 miles. Base assumption: 25,000 miles (conservative, includes safety margin for high-mileage fleet use).',
    defaultValue: 25000,
    unit: 'mi',
  },
  tire_set_cost: {
    id: 'tire_set_cost',
    label: 'Cost per Tire Set',
    definition: 'Cost of a full set of 4 tires including mounting and balancing. Cybercab is a small, purpose-built vehicle. Base assumption: $600 (includes margin for EV-rated tires and fleet service).',
    defaultValue: 600,
    unit: '$',
  },
  general_maintenance: {
    id: 'general_maintenance',
    label: 'General Maintenance',
    definition: 'Annual cost for non-tire maintenance: brake pads (~$100, minimal due to regen), cabin air filter (~$50), wiper blades (~$30), 12V battery (~$50 amortized), coolant (~$50 amortized), suspension/alignment (~$100 amortized). Base assumption: $500/yr (includes safety margin).',
    defaultValue: 500,
    unit: '$/yr',
  },
  insurance_cost: {
    id: 'insurance_cost',
    label: 'Insurance',
    definition: 'Annual commercial auto insurance per vehicle. Autonomous vehicle premiums are higher initially due to novelty, but Tesla can self-insure at scale using its own insurance product. Base assumption: $5,000/yr (conservative — assumes early-stage commercial premiums, not mature self-insurance rates).',
    defaultValue: 5000,
    unit: '$/yr',
  },
  remote_ops_cost: {
    id: 'remote_ops_cost',
    label: 'Remote Operations',
    formula: 'Operator Cost ÷ Vehicles per Operator',
    definition: 'Annual cost of human remote oversight per vehicle. Operators monitor multiple vehicles for edge cases — stuck situations, passenger issues, unusual conditions. Cost decreases as autonomy improves and ratio increases.',
    children: ['remote_ops_operator_cost', 'remote_ops_ratio'],
    unit: '$/yr',
  },
  remote_ops_operator_cost: {
    id: 'remote_ops_operator_cost',
    label: 'Operator Annual Cost',
    definition: 'Fully loaded annual cost per remote operator, including salary, benefits, workstation, office space, and software. Base assumption: $70,000/yr.',
    defaultValue: 70000,
    unit: '$/yr',
  },
  remote_ops_ratio: {
    id: 'remote_ops_ratio',
    label: 'Vehicles per Operator',
    definition: 'Number of robotaxis monitored by one remote operator. Depends on autonomy maturity and intervention frequency. Currently ~3:1 in early deployment, near-term target ~10:1. Base assumption: 15 vehicles per operator (between near-term target and mature operations).',
    defaultValue: 15,
    unit: 'vehicles',
  },
  cleaning_cost: {
    id: 'cleaning_cost',
    label: 'Cleaning',
    definition: 'Annual interior/exterior cleaning cost per vehicle. Includes quick cleans between rides (2-3x/day) and weekly deep cleans. Cybercab is designed for easy cleaning — hard plastic interior with drain holes. Can be partially automated with depot cleaning stations. Base assumption: $2,500/yr (between fleet model estimate of $1,700 and early manual operations overhead).',
    defaultValue: 2500,
    unit: '$/yr',
  },
  connectivity_cost: {
    id: 'connectivity_cost',
    label: 'Connectivity',
    definition: 'Annual LTE/5G data cost per vehicle for telemetry, navigation, HD maps, and remote operations video feeds. Fleet data plans are significantly cheaper than consumer rates. Base assumption: $600/yr.',
    defaultValue: 600,
    unit: '$/yr',
  },
  parking_cost: {
    id: 'parking_cost',
    label: 'Depot Parking',
    formula: '(Spot Monthly Cost × 12) ÷ Vehicles per Spot',
    definition: 'Annual depot/lot cost per vehicle for overnight parking, charging, cleaning, and staging. Located in low-cost industrial/suburban areas. Not every vehicle needs a dedicated spot — staggered shifts mean multiple vehicles share one space.',
    children: ['spot_monthly_cost', 'vehicles_per_spot'],
    unit: '$/yr',
  },
  spot_monthly_cost: {
    id: 'spot_monthly_cost',
    label: 'Spot Monthly Cost',
    definition: 'Monthly lease cost per parking spot in an industrial/suburban depot lot. Varies significantly by market — Austin much cheaper than SF. Base assumption: $100/month.',
    defaultValue: 100,
    unit: '$/mo',
  },
  vehicles_per_spot: {
    id: 'vehicles_per_spot',
    label: 'Vehicles per Spot',
    definition: 'Number of vehicles sharing one depot parking spot. In a 24/7 operation with staggered charging and driving schedules, not every vehicle is parked at the same time. Base assumption: 2 vehicles per spot.',
    defaultValue: 2,
    unit: 'vehicles',
  },
  overhead_cost: {
    id: 'overhead_cost',
    label: 'Overhead',
    definition: 'Annual catch-all for miscellaneous per-vehicle operating costs not covered elsewhere. Includes: payment processing fees (~$900/yr at 2.5% of revenue), regulatory and AV operating permits (~$300/yr), roadside assistance and towing for breakdowns (~$300/yr), minor damage repair below insurance deductible (~$300/yr), and customer support allocation (~$200/yr). Base assumption: $2,000/yr.',
    defaultValue: 2000,
    unit: '$/yr',
  },
  tax_per_vehicle: {
    id: 'tax_per_vehicle',
    label: 'Tax per Vehicle',
    shortLabel: 'Tax/Vehicle',
    formula: '(Rev/Vehicle − Cost/Vehicle) × Tax Rate',
    definition: 'Corporate income tax on per-vehicle operating profit. Federal rate is 21%, blended state rate ~4-5% (weighted toward low-tax states like TX, AZ, NV), offset by depreciation and R&D credits.',
    children: ['effective_tax_rate'],
    unit: '$/yr',
  },
  effective_tax_rate: {
    id: 'effective_tax_rate',
    label: 'Effective Tax Rate',
    definition: 'Blended effective corporate tax rate applied to operating profit. Includes federal (21%) + blended state (~4-5%) minus credits/deductions (~2-3%). Base assumption: 23%.',
    defaultValue: 23,
    unit: '%',
  },
  capex: {
    id: 'capex',
    label: 'Capital Expenditures',
    shortLabel: 'CapEx',
    formula: 'Vehicle Purchases + Infrastructure',
    definition: 'Upfront investment in fleet vehicles and supporting infrastructure. Heavy in early years, decreases as fleet matures.',
    children: ['vehicle_purchases', 'infrastructure'],
    unit: '$total',
  },
  vehicle_purchases: {
    id: 'vehicle_purchases',
    label: 'Vehicle Purchases',
    formula: 'New Units × Cost per Vehicle',
    definition: 'Cost of acquiring new Cybercabs or Model Ys for the fleet. Cybercab target cost ~$30k, significantly below competitors.',
    children: ['new_units', 'cost_per_vehicle'],
    unit: '$total',
  },
  new_units: {
    id: 'new_units',
    label: 'New Units',
    definition: 'Number of new vehicles added in the year. Driven by the Fleet Size ramp schedule.',
    unit: 'vehicles',
  },
  cost_per_vehicle: {
    id: 'cost_per_vehicle',
    label: 'Cost per Vehicle',
    definition: 'Manufacturing cost per robotaxi unit. Cybercab target ~$25K–$30K, significantly below competitors due to purpose-built design (no steering wheel/pedals).',
    unit: '$',
    defaultValue: 25_000,
  },
  infrastructure: {
    id: 'infrastructure',
    label: 'Infrastructure',
    formula: 'New Units × Infra Cost per Vehicle',
    definition: 'Charging depots, cleaning facilities, and remote operations centers needed to support the fleet.',
    children: ['infra_new_units', 'infra_cost_per_vehicle'],
    unit: '$total',
  },
  infra_new_units: {
    id: 'infra_new_units',
    label: 'New Units',
    definition: 'Number of new vehicles requiring infrastructure buildout. Same as fleet ramp schedule.',
    unit: 'vehicles',
  },
  infra_cost_per_vehicle: {
    id: 'infra_cost_per_vehicle',
    label: 'Infra Cost per Vehicle',
    definition: 'Infrastructure investment per new vehicle: charging depots, cleaning bays, remote ops centers. Amortized across fleet.',
    unit: '$',
    defaultValue: 5_000,
  },
}

export const DCF_ROOT = 'dcf'

export const PROJ_INPUT_IDS = ['cost_per_vehicle', 'infra_cost_per_vehicle'] as const

// ── Revenue per Vehicle computation ──────────────────────

/** IDs of all leaf inputs in the rev_per_vehicle subtree */
export const REV_INPUT_IDS = [
  'utilization', 'avg_trip_length', 'avg_speed',
  'avg_empty_distance', 'load_unload_time', 'base_fare', 'fare_per_mile',
] as const

export type RevInputId = typeof REV_INPUT_IDS[number]

/** Compute all rev_per_vehicle intermediate + final values from leaf inputs */
export function computeRevPerVehicle(overrides: Partial<Record<RevInputId, number>> = {}): Record<string, number> {
  const v = (id: RevInputId) => overrides[id] ?? DCF_NODES[id].defaultValue!

  const utilization = v('utilization') / 100
  const active_hours = utilization * 24
  const drive_time = (v('avg_trip_length') / v('avg_speed')) * 60
  const repositioning_time = (v('avg_empty_distance') / v('avg_speed')) * 60
  const trip_cycle_time = drive_time + repositioning_time + v('load_unload_time')
  const trips_per_day = (active_hours * 60) / trip_cycle_time
  const rev_per_trip = v('base_fare') + v('avg_trip_length') * v('fare_per_mile')
  const rev_per_vehicle = trips_per_day * rev_per_trip * 365

  return {
    utilization: v('utilization'),
    active_hours,
    avg_trip_length: v('avg_trip_length'),
    avg_speed: v('avg_speed'),
    drive_time,
    avg_empty_distance: v('avg_empty_distance'),
    repositioning_time,
    load_unload_time: v('load_unload_time'),
    trip_cycle_time,
    trips_per_day,
    base_fare: v('base_fare'),
    fare_per_mile: v('fare_per_mile'),
    rev_per_trip,
    rev_per_vehicle,
  }
}

// ── Cost per Vehicle computation ────────────────────────

/** IDs of all leaf inputs in the cost_per_vehicle subtree */
export const COST_INPUT_IDS = [
  'kwh_per_mile', 'price_per_kwh',
  'tire_life', 'tire_set_cost', 'general_maintenance',
  'insurance_cost', 'remote_ops_operator_cost', 'remote_ops_ratio',
  'cleaning_cost', 'connectivity_cost',
  'spot_monthly_cost', 'vehicles_per_spot',
  'overhead_cost', 'effective_tax_rate',
] as const

export type CostInputId = typeof COST_INPUT_IDS[number]

/** Compute all cost_per_vehicle intermediate + final values from leaf inputs + rev values */
export function computeCostPerVehicle(
  revValues: Record<string, number>,
  overrides: Partial<Record<CostInputId, number>> = {},
): Record<string, number> {
  const v = (id: CostInputId) => overrides[id] ?? DCF_NODES[id].defaultValue!

  const trips_per_day = revValues.trips_per_day ?? 0
  const avg_trip_length = revValues.avg_trip_length ?? 0
  const avg_empty_distance = revValues.avg_empty_distance ?? 0

  const annual_distance = trips_per_day * (avg_trip_length + avg_empty_distance) * 365
  const kwh_per_mile = v('kwh_per_mile')
  const price_per_kwh = v('price_per_kwh')
  const charging_cost = annual_distance * kwh_per_mile * price_per_kwh

  const tire_life = v('tire_life')
  const tire_set_cost = v('tire_set_cost')
  const tire_cost = (annual_distance / tire_life) * tire_set_cost

  const general_maintenance = v('general_maintenance')
  const maintenance_cost = tire_cost + general_maintenance

  const insurance_cost = v('insurance_cost')

  const remote_ops_operator_cost = v('remote_ops_operator_cost')
  const remote_ops_ratio = v('remote_ops_ratio')
  const remote_ops_cost = remote_ops_operator_cost / remote_ops_ratio

  const cleaning_cost = v('cleaning_cost')
  const connectivity_cost = v('connectivity_cost')

  const spot_monthly_cost = v('spot_monthly_cost')
  const vehicles_per_spot = v('vehicles_per_spot')
  const parking_cost = (spot_monthly_cost * 12) / vehicles_per_spot

  const overhead_cost = v('overhead_cost')

  const cost_per_vehicle = charging_cost + maintenance_cost + insurance_cost + remote_ops_cost + cleaning_cost + connectivity_cost + parking_cost + overhead_cost

  const rev_per_vehicle = revValues.rev_per_vehicle ?? 0
  const effective_tax_rate = v('effective_tax_rate')
  const operating_profit = rev_per_vehicle - cost_per_vehicle
  const tax_per_vehicle = Math.max(0, operating_profit) * (effective_tax_rate / 100)
  const unit_economics = rev_per_vehicle - cost_per_vehicle - tax_per_vehicle

  return {
    annual_distance,
    kwh_per_mile,
    price_per_kwh,
    charging_cost,
    tire_life,
    tire_set_cost,
    tire_cost,
    general_maintenance,
    maintenance_cost,
    insurance_cost,
    remote_ops_operator_cost,
    remote_ops_ratio,
    remote_ops_cost,
    cleaning_cost,
    connectivity_cost,
    spot_monthly_cost,
    vehicles_per_spot,
    parking_cost,
    overhead_cost,
    cost_per_vehicle,
    effective_tax_rate,
    tax_per_vehicle,
    unit_economics,
  }
}

// ── 10-Year Projection ────────────────────────────────────

export interface ProjectionInputs {
  newVehiclesByYear: number[]
  vehicleCost: number
  infraCostPerVehicle: number
  vehicleUsefulLife: number
  wacc: number
  terminalGrowthRate: number
  startYear: number
}

export interface ProjectionYear {
  year: number
  fleetSize: number
  newVehicles: number
  revenue: number
  opCost: number
  depreciation: number
  taxableIncome: number
  tax: number
  netIncome: number
  ocf: number
  vehicleCapex: number
  infraCapex: number
  totalCapex: number
  fcf: number
  discountFactor: number
  pvFcf: number
}

export interface ProjectionResult {
  years: ProjectionYear[]
  terminalFcf: number
  terminalValue: number
  pvTerminalValue: number
  totalPvFcf: number
  equityValue: number
}

export const DEFAULT_NEW_VEHICLES = [5_000, 50_000, 150_000, 300_000, 600_000, 1_000_000, 1_500_000, 2_000_000, 2_500_000, 3_000_000]

export const DEFAULT_PROJECTION_INPUTS: ProjectionInputs = {
  newVehiclesByYear: [...DEFAULT_NEW_VEHICLES],
  vehicleCost: 25_000,
  infraCostPerVehicle: 5_000,
  vehicleUsefulLife: 5,
  wacc: 12,
  terminalGrowthRate: 3,
  startYear: 2026,
}

export function computeProjection(
  inputs: ProjectionInputs,
  revPerVehicle: number,
  costPerVehicle: number,
  taxRate: number,
): ProjectionResult {
  const { newVehiclesByYear, vehicleCost, infraCostPerVehicle,
    vehicleUsefulLife, wacc, terminalGrowthRate, startYear } = inputs

  const waccDec = wacc / 100
  const taxDec = taxRate / 100
  const depPerVehicle = vehicleCost / vehicleUsefulLife

  const cohorts: { year: number; count: number }[] = []
  const years: ProjectionYear[] = []

  let cumulativeFleet = 0

  for (let t = 0; t < 10; t++) {
    const year = startYear + t
    const newVehicles = newVehiclesByYear[t] ?? 0
    cumulativeFleet += newVehicles
    const fleetSize = cumulativeFleet

    cohorts.push({ year: t, count: newVehicles })

    const revenue = fleetSize * revPerVehicle
    const opCost = fleetSize * costPerVehicle

    // Sum depreciation from all active cohorts
    let depreciation = 0
    for (const cohort of cohorts) {
      if (t - cohort.year < vehicleUsefulLife) {
        depreciation += cohort.count * depPerVehicle
      }
    }

    const taxableIncome = revenue - opCost - depreciation
    const tax = Math.max(0, taxableIncome) * taxDec
    const netIncome = taxableIncome - tax
    const ocf = netIncome + depreciation // add back non-cash

    const vehicleCapex = newVehicles * vehicleCost
    const infraCapex = newVehicles * infraCostPerVehicle
    const totalCapex = vehicleCapex + infraCapex
    const fcf = ocf - totalCapex

    const discountFactor = 1 / Math.pow(1 + waccDec, t + 1)
    const pvFcf = fcf * discountFactor

    years.push({
      year, fleetSize, newVehicles,
      revenue, opCost, depreciation, taxableIncome, tax, netIncome, ocf,
      vehicleCapex, infraCapex, totalCapex, fcf,
      discountFactor, pvFcf,
    })

  }

  const lastFcf = years[9].fcf
  const termGrowthDec = terminalGrowthRate / 100
  const terminalFcf = lastFcf * (1 + termGrowthDec)
  const terminalValue = waccDec > termGrowthDec ? terminalFcf / (waccDec - termGrowthDec) : 0
  const pvTerminalValue = terminalValue * years[9].discountFactor

  const totalPvFcf = years.reduce((sum, y) => sum + y.pvFcf, 0)
  const equityValue = totalPvFcf + pvTerminalValue

  return { years, terminalFcf, terminalValue, pvTerminalValue, totalPvFcf, equityValue }
}

export function formatProjectionValue(value: number, type: 'count' | 'currency' | 'factor'): string {
  if (type === 'count') {
    const abs = Math.abs(value)
    if (abs >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`
    if (abs >= 1_000) return `${(value / 1_000).toFixed(0)}K`
    return value.toLocaleString()
  }
  if (type === 'currency') {
    const abs = Math.abs(value)
    let formatted: string
    if (abs >= 1_000_000_000_000) formatted = `$${(abs / 1_000_000_000_000).toFixed(1)}T`
    else if (abs >= 1_000_000_000) formatted = `$${(abs / 1_000_000_000).toFixed(1)}B`
    else if (abs >= 1_000_000) formatted = `$${(abs / 1_000_000).toFixed(0)}M`
    else if (abs >= 1_000) formatted = `$${(abs / 1_000).toFixed(0)}K`
    else formatted = `$${abs.toFixed(0)}`
    return value < 0 ? `(${formatted})` : formatted
  }
  if (type === 'factor') {
    return `${value.toFixed(3)}x`
  }
  return `${value}`
}

/** Format a computed value with its unit */
export function formatDcfValue(nodeId: string, value: number): string {
  const node = DCF_NODES[nodeId]
  const unit = node?.unit
  if (unit === '$') return value >= 1000 ? `$${Math.round(value).toLocaleString()}` : `$${value.toFixed(2)}`
  if (unit === '$/yr') return `$${Math.round(value).toLocaleString()}`
  if (unit === '$/mi') return `$${value.toFixed(2)}/mi`
  if (unit === '%') return `${value}%`
  if (unit === 'min') return `${value.toFixed(1)} min`
  if (unit === 'hrs') return `${value.toFixed(1)} hrs`
  if (unit === 'mph') return `${value} mph`
  if (unit === 'mi') return `${value} mi`
  if (unit === 'trips') return `${value.toFixed(1)}`
  if (unit === 'kWh/mi') return `${value} kWh/mi`
  if (unit === '$/kWh') return `$${value.toFixed(2)}/kWh`
  if (unit === 'mi/yr') return `${Math.round(value).toLocaleString()} mi/yr`
  if (unit === 'vehicles') {
    if (value >= 1_000_000) return `${(value / 1_000_000).toFixed(1)}M`
    if (value >= 1_000) return `${(value / 1_000).toFixed(0)}K`
    return `${value}`
  }
  if (unit === '$/mo') return `$${value}/mo`
  if (unit === '$total') {
    const abs = Math.abs(value)
    const sign = value < 0 ? '-' : ''
    if (abs >= 1_000_000_000_000) return `${sign}$${(abs / 1_000_000_000_000).toFixed(1)}T`
    if (abs >= 1_000_000_000) return `${sign}$${(abs / 1_000_000_000).toFixed(1)}B`
    if (abs >= 1_000_000) return `${sign}$${(abs / 1_000_000).toFixed(1)}M`
    if (abs >= 1_000) return `${sign}$${(abs / 1_000).toFixed(0)}K`
    return `${sign}$${abs}`
  }
  return `${value}`
}
